version: 2
jobs:
  build:
    working_directory: ~/lambda_py
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout    
      - add_ssh_keys:
          fingerprints:
            - "d5:ad:14:d7:65:c7:53:29:68:c4:6f:56:eb:ae:06:4c"
      - run:
          name: checkout TF stuff
          command: |
            echo $infra_repo
            git clone $infra_repo
      - run:
          name: test
          command: echo "that's it"

      - deploy:
          name: 'Deploy code'
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Will deploy to aws"
            fi
