version: 2
jobs:
  build:
    working_directory: ~/lambda_py
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3d:01:3f:2b:2a:c7:1b:46:76:42:80:ec:b7:8c:ec:c0"
      - checkout
      - run:
          name: checkout TF stuff
          command: git clone $infra_repo
      - run:
          name: test
          command: echo "that's it"

      - deploy:
          name: 'Deploy code'
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Will deploy to aws"
            fi
