version: 2
jobs:
  build:
    working_directory: ~
    # /lambda_py
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints:
      #       - "d5:ad:14:d7:65:c7:53:29:68:c4:6f:56:eb:ae:06:4c"
      # - run:
      #     name: stupid
      #     command: echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      - run:
          name: checkout TF stuff
          command: |
            # cat << EOF >> ~/.gitconfig
            # [user]
            # name = Eugen Cocalea
            # email = eugen.cocalea@gmail.com
            # EOF
            # cat << EOF >> ~/.ssh/config
            # Host github.com
            #   HostName github.com
            #   User eugen.cocalea@gmail.com
            #   IdentityFile ~/.ssh/id_rsa
            # EOF
            # cat ~/.ssh/id_rsa
            # cat ~/.gitconfig
            # ssh-add ~/.ssh/id_rsa
            echo Checking out $infra_repo
            git clone "$infra_repo" --verbose
      - run:
          name: test
          command: echo "that's it"

      - deploy:
          name: 'Deploy code'
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Will deploy to aws"
            fi
